// Hand-written app-level type aliases. Kept SEPARATE from database.ts because
// database.ts is regenerated by `supabase gen types typescript --linked` and
// any hand-edits there get wiped. Anything you'd be tempted to add to
// database.ts goes here instead.

export type PublicUser = {
  id: string;
  display_name: string;
  must_change_pin: boolean;
  is_admin: boolean;
};
